/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package practice;

import javax.swing.JScrollPane;
import javax.swing.JTextPane;

/**
 *
 * @author alxx_pc
 */
public class FrmiPractic extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmiPractic
     */
    public FrmiPractic() {
        initComponents();
    
 jscrNumlineas.setNextFocusableComponent(txPcodigo);
TextLineNumber tln = new TextLineNumber(txPcodigo);
jscrNumlineas.setRowHeaderView( tln );

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txPcodigo = new javax.swing.JTextPane();
        jscrNumlineas = new javax.swing.JScrollPane();

        txPcodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txPcodigoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(txPcodigo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jscrNumlineas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(jscrNumlineas))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txPcodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txPcodigoKeyReleased
        System.out.println(txPcodigo.getText().replaceAll("[\n\r]",""));
    }//GEN-LAST:event_txPcodigoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jscrNumlineas;
    private javax.swing.JTextPane txPcodigo;
    // End of variables declaration//GEN-END:variables
}
