/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelo.Nodo;
import modelo.NodoToken;
import modelo.Token;

/**
 *
 * @author alxx_pc
 */
public class FrmiTokens extends javax.swing.JInternalFrame {
      ArrayList<Nodo> lista= new ArrayList();
       ArrayList<Nodo> auxl= new ArrayList();
       
    public FrmiTokens() {
            
        initComponents();
     ImageIcon imagen= new ImageIcon("/images/anterior2.jpg");
             btnInicio= new JButton();
             btnInicio.setBounds(0, 0, 20, 20);
          Icon icono= new ImageIcon(imagen.getImage().getScaledInstance(btnInicio.getWidth(), btnInicio.getHeight(), Image.SCALE_DEFAULT));
   btnInicio.setIcon(icono);
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnEnteros = new javax.swing.JButton();
        btnDecimales = new javax.swing.JButton();
        btnId = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        txtExpresion = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        btnReroceder = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        btnPlayme = new javax.swing.JButton();
        btnLista = new javax.swing.JButton();
        btnaux = new javax.swing.JButton();
        btnLlenar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        jLabel1.setText("Expresión:");

        btnEnteros.setText("#E");
        btnEnteros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterosActionPerformed(evt);
            }
        });

        btnDecimales.setText("#D");

        btnId.setText("ID");

        jLabel2.setText("Descripción del Token");

        jLabel3.setText("Expresión del Token");

        btnAdd.setText("ADD =)");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Descripción", "Expresión"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnInicio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnUltimo.setText("Al final");
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        btnReroceder.setText("Retroceder");
        btnReroceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRerocederActionPerformed(evt);
            }
        });

        btnSiguiente.setText("Adelantar");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReroceder, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUltimo)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReroceder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSiguiente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUltimo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPlayme.setText("Play me");
        btnPlayme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaymeActionPerformed(evt);
            }
        });

        btnLista.setText("lista");
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });

        btnaux.setText("aux");
        btnaux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnauxActionPerformed(evt);
            }
        });

        btnLlenar.setText("llenar tabla");
        btnLlenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLlenarActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");

        jMenuItem1.setText("Abrir");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Guardar");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEnteros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDecimales)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnId))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescripcion)
                            .addComponent(txtExpresion, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(btnAdd))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPlayme)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnLista)
                                .addGap(18, 18, 18)
                                .addComponent(btnLlenar))
                            .addComponent(btnaux))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnEnteros)
                    .addComponent(btnDecimales)
                    .addComponent(btnId))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtExpresion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAdd)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btnPlayme)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLista)
                            .addComponent(btnLlenar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnaux)))
                .addContainerGap(221, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 DefaultTableModel tabla;
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
Nodo token= new Nodo(txtDescripcion.getText(), txtExpresion.getText());
lista.add(token);
tabla= (DefaultTableModel) jTable1.getModel();
        String fila[]=  new  String[2];
        fila[0]=token.getDescripcion();
        fila[1]=token.getLexema();
    tabla.addRow(fila);
     
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnPlaymeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaymeActionPerformed
   removerfilas();
    }//GEN-LAST:event_btnPlaymeActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
       moveralinicio();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
        for (int i = 0; i <lista.size(); i++) {
            System.out.println(lista.get(i).getDescripcion()+"---"+lista.get(i).getLexema());
        }
    }//GEN-LAST:event_btnListaActionPerformed

    private void btnauxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnauxActionPerformed
          for (int i = 0; i <auxl.size(); i++) {
            System.out.println(auxl.get(i).getDescripcion()+"---"+auxl.get(i).getLexema());
        }
    }//GEN-LAST:event_btnauxActionPerformed

    private void btnRerocederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRerocederActionPerformed
       anterior();
    }//GEN-LAST:event_btnRerocederActionPerformed

    private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
        moveralfinal();
    }//GEN-LAST:event_btnUltimoActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
       siguiente();
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnLlenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLlenarActionPerformed
        llenartabla();
    }//GEN-LAST:event_btnLlenarActionPerformed

    private void btnEnterosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterosActionPerformed
       
    }//GEN-LAST:event_btnEnterosActionPerformed
public void moveralinicio (){
    try{
  int tam= lista.size();
    int y =jTable1.getSelectedRow();
Nodo x=lista.get(y);
 lista.remove(y);
// ArrayList<Nodo> aux= new ArrayList<>();
 Nodo[]aux= new Nodo[tam-1];
        for (int i = 0; i < tam-1; i++) {
          aux[i]=lista.get(i);
        }
                
 lista.clear();
 lista.add(x);
        for (int i = 0; i < tam-1; i++) {
            lista.add(aux[i]);
        }
        for (int i = 0; i < lista.size(); i++) {
            System.out.println(lista.get(i).getDescripcion()+"--lista"); 
        }
        for (int i = 0; i < aux.length; i++) {
            System.out.println(aux[i].getDescripcion()+"--aux");
        }
        
   llenartabla();
   }catch(Exception e){}
}
public void moveralfinal (){
    try{
  int tam= lista.size();
    int y =jTable1.getSelectedRow();
Nodo x=lista.get(y);
 lista.remove(y);
 Nodo[]aux= new Nodo[tam-1];
        for (int i = 0; i < tam-1; i++) {
          aux[i]=lista.get(i);
        }              
 lista.clear();
        for (int i = 0; i < tam-1; i++) {
            lista.add(aux[i]);
        }
        lista.add(x);
           llenartabla();
   }catch(Exception e){}
}
public void anterior (){
    try{
    int y =jTable1.getSelectedRow();
    int x=y-1;
Nodo actual=lista.get(y);
Nodo anterior=lista.get(y-1);
 lista.remove(y);
 lista.remove(x);
lista.add(x, actual);
lista.add(y, anterior);
           llenartabla();
   }catch(Exception e){}
}
public void siguiente (){
    try{
    int arriba =jTable1.getSelectedRow();
    int abajo=arriba+1;
Nodo actual=lista.get(arriba);
Nodo siguiente=lista.get(abajo);
 lista.remove(arriba);
 lista.add(arriba, siguiente);
 lista.remove(abajo);
 lista.add(abajo,actual);


           llenartabla();
   }catch(Exception e){}
}
public void llenartabla(){
    try{
   removerfilas();
    for (int i = 0; i < lista.size(); i++) {
      String fila[]=  new  String[2]; 
        fila[0]=lista.get(i).getDescripcion();
        fila[1]=lista.get(i).getLexema();
        tabla.addRow(fila);
    }
      
   }catch(Exception e){} 
}
public void removerfilas(){
     try {
            DefaultTableModel modelo=(DefaultTableModel) jTable1.getModel();
            int filas=jTable1.getRowCount();
            for (int i = 0;filas>i; i++) {
                modelo.removeRow(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al limpiar la tabla.");
        }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDecimales;
    private javax.swing.JButton btnEnteros;
    private javax.swing.JButton btnId;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnLista;
    private javax.swing.JButton btnLlenar;
    private javax.swing.JButton btnPlayme;
    private javax.swing.JButton btnReroceder;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JButton btnaux;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtExpresion;
    // End of variables declaration//GEN-END:variables
}
