/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PnlLienzo.java
 *
 * Created on 23/01/2012, 02:12:05 PM
 */
package vista;

import java.awt.Graphics;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.Arrays;
import modelo.Estado;
import modelo.Relacion;

/**
 *
 * @author fabian
 */
public class PnlLienzo extends javax.swing.JPanel {

    /** Creates new form PnlLienzo */
    
    
    public Estado actual;
    public String relacionActual;
    
    
    
    public void paint(Graphics g)
    {
        super.paint(g);
        this.pintar();
    }
    
    
    private ArrayList<Estado>estados;
    
    public PnlLienzo() {
        initComponents();
        estados=new ArrayList<Estado>();
        actual=null;
        relacionActual="";
    }
    
    public void agregar(Estado e)
    {
        estados.add(e);
    }
    
    public void pintar()
    {
        Estado.dibujarVarios(estados);
    }

    public ArrayList<Estado> getEstados() {
        return estados;
    }

    public void setEstados(ArrayList<Estado> estados) {
        this.estados = estados;
    }

    public Estado buscar(String e)
    {
        for (Estado estado : estados) {
            if(estado.getNombre().equals(e))
                return estado;
        }
        return null;
    }
    public ArrayList<String> getStringRelaciones(Estado e)
    {
        ArrayList<String>aux=new ArrayList<String>();
        for (Relacion  r: e.getRelaciones()) {
                            
            String [] aux2=r.getNombre().split("|");
            aux.addAll(Arrays.asList(aux2));
        }
        while(aux.remove(""));
        return aux;
    }
    
    public void limpiar()
    {
        MouseListener []m=this.getMouseListeners();
        for (int i = 0; i < m.length; i++) {
            this.removeMouseListener(m[i]);
        }
        estados=new ArrayList<Estado>(); 
    }
    
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
