
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jul 15 12:03:59 COT 2015
//----------------------------------------------------

package modello;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PARENC = 38;
  public static final int PARENA = 37;
  public static final int DISTINTO = 14;
  public static final int Y = 23;
  public static final int POR = 20;
  public static final int PROGRAMA = 2;
  public static final int IMPRIMIR = 9;
  public static final int ENTERO = 6;
  public static final int SI = 22;
  public static final int O = 13;
  public static final int DESDE = 19;
  public static final int ESTRUCTURA = 4;
  public static final int PARAR = 27;
  public static final int DIVIDENDO = 17;
  public static final int CICLO = 40;
  public static final int FIN = 10;
  public static final int IGUAL = 18;
  public static final int MIENTRAS = 12;
  public static final int NENTERO = 31;
  public static final int ID = 5;
  public static final int EOF = 0;
  public static final int DECIMAL = 7;
  public static final int error = 1;
  public static final int COMA = 36;
  public static final int CADENA = 8;
  public static final int MENOS = 16;
  public static final int MENOR = 25;
  public static final int NDECIMAL = 32;
  public static final int VECTOR = 24;
  public static final int PCOMA = 30;
  public static final int MAYOR = 11;
  public static final int NO = 28;
  public static final int MAYORIG = 29;
  public static final int DECLARACIONES = 3;
  public static final int DCADENA = 33;
  public static final int FALSO = 35;
  public static final int MENORIG = 26;
  public static final int BOOLEANO = 15;
  public static final int VERDADERO = 34;
  public static final int INICIO = 39;
  public static final int MAS = 21;
}

