/* The following code was generated by JFlex 1.4.3 on 15/07/15 10:30 */

package modello;
import java_cup.runtime.Symbol;

/*
Directivas:
public: clase publica
cup: compatibilidad con cup
full: extender el alfabeto con todos los valores de 8 bits
line: agrega la variable int yyline, para indicar la fila del lexema
char: agrega la variable int yychar, indica el indice del primer caracter del lexema
ignorecase: validar, indistitntamente si la letra es mayuscula o minuscula
eofval: especifica un valor de retorno al final del archivo
*/


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 15/07/15 10:30 from the specification file
 * <tt>Lexico.flex</tt>
 */
public class Yylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  4,  0,  4,  4,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     4, 35,  0,  0,  0,  0, 36, 44, 41, 42, 30, 29, 40,  5,  6, 31, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  0, 38, 32, 34, 33,  0, 
     0, 45,  2, 43, 13, 20, 23,  2,  2, 24,  2,  2,  2,  2, 46,  2, 
     7,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  0,  0,  0,  0,  3, 
     0, 11, 26, 15, 28, 14, 39, 10,  2, 17,  2,  2, 16, 12, 18,  9, 
    25,  2,  8, 19, 21, 22, 27,  2,  2,  2,  2,  0, 37,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\15\3\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\3\1\20\1\21\1\22\1\3\1\1\1\23"+
    "\5\3\1\24\10\3\1\25\1\26\1\27\2\3\1\0"+
    "\6\3\1\30\12\3\1\0\20\3\1\0\10\3\1\31"+
    "\4\3\1\32\1\33\1\34\1\0\3\3\1\35\1\36"+
    "\2\3\1\37\2\3\1\40\1\3\1\0\7\3\1\41"+
    "\1\0\1\42\1\43\2\3\1\44\1\45\1\3\1\0"+
    "\2\3\1\46\1\0\1\3\1\47\1\50\2\3\1\51";

  private static int [] zzUnpackAction() {
    int [] result = new int[148];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\57\0\136\0\215\0\57\0\274\0\353\0\u011a"+
    "\0\u0149\0\u0178\0\u01a7\0\u01d6\0\u0205\0\u0234\0\u0263\0\u0292"+
    "\0\u02c1\0\u02f0\0\u031f\0\274\0\57\0\57\0\u034e\0\u037d"+
    "\0\57\0\57\0\57\0\57\0\57\0\u03ac\0\57\0\57"+
    "\0\57\0\u03db\0\u040a\0\u0439\0\u0468\0\u0497\0\u04c6\0\u04f5"+
    "\0\u0524\0\215\0\u0553\0\u0582\0\u05b1\0\u05e0\0\u060f\0\u063e"+
    "\0\u066d\0\u069c\0\57\0\57\0\57\0\u06cb\0\u06fa\0\u0729"+
    "\0\u0758\0\u0787\0\u07b6\0\u07e5\0\u0814\0\u0843\0\215\0\u0872"+
    "\0\u08a1\0\u08d0\0\u08ff\0\u092e\0\u095d\0\u098c\0\u09bb\0\u09ea"+
    "\0\u0a19\0\u0a48\0\u0a77\0\u0aa6\0\u0ad5\0\u0b04\0\u0b33\0\u0b62"+
    "\0\u0b91\0\u0bc0\0\u0bef\0\u0c1e\0\u0c4d\0\u0c7c\0\u0cab\0\u0cda"+
    "\0\u0d09\0\u0d38\0\u0d67\0\u0d96\0\u0dc5\0\u0df4\0\u0e23\0\u0e52"+
    "\0\u0e81\0\u0eb0\0\u0edf\0\215\0\u0f0e\0\u0f3d\0\u0f6c\0\u0f9b"+
    "\0\215\0\215\0\215\0\u0fca\0\u0ff9\0\u1028\0\u1057\0\215"+
    "\0\215\0\u1086\0\u10b5\0\215\0\u10e4\0\u1113\0\215\0\u1142"+
    "\0\u1171\0\u11a0\0\u11cf\0\u11fe\0\u122d\0\u125c\0\u128b\0\u12ba"+
    "\0\215\0\u12e9\0\215\0\215\0\u1318\0\u1347\0\215\0\215"+
    "\0\u1376\0\u13a5\0\u13d4\0\u1403\0\215\0\u1432\0\u1461\0\215"+
    "\0\57\0\u1490\0\u14bf\0\215";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[148];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\2\1\5\1\6\1\2\1\7"+
    "\4\4\1\10\1\11\1\12\1\13\3\4\1\14\1\15"+
    "\2\4\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\2\4"+
    "\60\0\1\3\4\0\1\44\51\0\3\4\3\0\26\4"+
    "\12\0\1\4\3\0\1\4\1\0\2\4\1\0\1\3"+
    "\56\0\3\4\3\0\1\4\1\45\24\4\12\0\1\4"+
    "\3\0\1\4\1\0\2\4\1\0\3\4\3\0\12\4"+
    "\1\46\13\4\12\0\1\4\3\0\1\4\1\0\2\4"+
    "\1\0\3\4\3\0\7\4\1\47\16\4\12\0\1\4"+
    "\3\0\1\4\1\0\2\4\1\0\3\4\3\0\13\4"+
    "\1\50\12\4\12\0\1\4\3\0\1\4\1\0\2\4"+
    "\1\0\3\4\3\0\4\4\1\51\21\4\12\0\1\4"+
    "\3\0\1\4\1\0\2\4\1\0\3\4\3\0\12\4"+
    "\1\52\13\4\12\0\1\4\3\0\1\4\1\0\2\4"+
    "\1\0\3\4\3\0\14\4\1\53\11\4\12\0\1\4"+
    "\3\0\1\4\1\0\2\4\1\0\3\4\3\0\12\4"+
    "\1\54\13\4\12\0\1\4\3\0\1\4\1\0\2\4"+
    "\1\0\3\4\3\0\5\4\1\55\5\4\1\56\12\4"+
    "\12\0\1\4\3\0\1\4\1\0\2\4\1\0\3\4"+
    "\3\0\4\4\1\57\21\4\12\0\1\4\3\0\1\4"+
    "\1\0\2\4\1\0\3\4\3\0\2\4\1\60\23\4"+
    "\12\0\1\4\3\0\1\4\1\0\2\4\1\0\3\4"+
    "\3\0\7\4\1\61\16\4\12\0\1\4\3\0\1\4"+
    "\1\0\2\4\1\0\3\4\3\0\7\4\1\62\16\4"+
    "\12\0\1\4\3\0\1\4\1\0\2\4\41\0\1\63"+
    "\1\64\56\0\1\65\15\0\3\4\3\0\4\4\1\66"+
    "\21\4\12\0\1\4\3\0\1\4\1\0\2\4\1\0"+
    "\3\4\3\0\12\4\1\67\13\4\12\0\1\4\3\0"+
    "\1\4\1\0\2\4\51\0\1\70\6\0\1\44\56\0"+
    "\3\4\3\0\2\4\1\71\23\4\12\0\1\4\3\0"+
    "\1\4\1\0\2\4\1\0\3\4\3\0\7\4\1\72"+
    "\16\4\12\0\1\4\3\0\1\4\1\0\2\4\1\0"+
    "\3\4\3\0\10\4\1\73\15\4\12\0\1\4\3\0"+
    "\1\4\1\0\2\4\1\0\3\4\3\0\16\4\1\74"+
    "\7\4\12\0\1\4\3\0\1\4\1\0\2\4\1\0"+
    "\3\4\3\0\25\4\1\75\12\0\1\4\3\0\1\4"+
    "\1\0\2\4\1\0\3\4\3\0\16\4\1\76\7\4"+
    "\12\0\1\4\3\0\1\4\1\0\2\4\1\0\3\4"+
    "\3\0\13\4\1\77\12\4\12\0\1\4\3\0\1\4"+
    "\1\0\2\4\1\0\3\4\3\0\22\4\1\100\3\4"+
    "\12\0\1\4\3\0\1\4\1\0\2\4\1\0\3\4"+
    "\3\0\12\4\1\101\13\4\12\0\1\4\3\0\1\4"+
    "\1\0\2\4\1\0\3\4\3\0\1\4\1\102\24\4"+
    "\12\0\1\4\3\0\1\4\1\0\2\4\1\0\3\4"+
    "\3\0\2\4\1\103\23\4\12\0\1\4\3\0\1\4"+
    "\1\0\2\4\1\0\3\4\3\0\1\4\1\104\6\4"+
    "\1\105\15\4\12\0\1\4\3\0\1\4\1\0\2\4"+
    "\1\0\3\4\3\0\10\4\1\106\3\4\1\107\11\4"+
    "\12\0\1\4\3\0\1\4\1\0\2\4\1\0\3\4"+
    "\3\0\11\4\1\110\14\4\12\0\1\4\3\0\1\4"+
    "\1\0\2\4\1\0\3\4\3\0\10\4\1\111\15\4"+
    "\12\0\1\4\3\0\1\4\1\0\2\4\53\0\1\112"+
    "\4\0\3\4\3\0\3\4\1\113\22\4\12\0\1\4"+
    "\3\0\1\4\1\0\2\4\1\0\3\4\3\0\13\4"+
    "\1\114\12\4\12\0\1\4\3\0\1\4\1\0\2\4"+
    "\1\0\3\4\3\0\11\4\1\115\14\4\12\0\1\4"+
    "\3\0\1\4\1\0\2\4\1\0\3\4\3\0\7\4"+
    "\1\116\16\4\12\0\1\4\3\0\1\4\1\0\2\4"+
    "\1\0\3\4\3\0\7\4\1\117\16\4\12\0\1\4"+
    "\3\0\1\4\1\0\2\4\1\0\3\4\3\0\1\4"+
    "\1\120\24\4\12\0\1\4\3\0\1\4\1\0\2\4"+
    "\1\0\3\4\3\0\1\4\1\121\24\4\12\0\1\4"+
    "\3\0\1\4\1\0\2\4\1\0\3\4\3\0\10\4"+
    "\1\122\15\4\12\0\1\4\3\0\1\4\1\0\2\4"+
    "\1\0\3\4\3\0\4\4\1\123\21\4\12\0\1\4"+
    "\3\0\1\4\1\0\2\4\1\0\3\4\3\0\11\4"+
    "\1\124\14\4\12\0\1\4\3\0\1\4\1\0\2\4"+
    "\1\0\3\4\3\0\25\4\1\125\12\0\1\4\3\0"+
    "\1\4\1\0\2\4\1\0\3\4\3\0\16\4\1\126"+
    "\7\4\12\0\1\4\3\0\1\4\1\0\2\4\1\0"+
    "\3\4\3\0\12\4\1\127\13\4\12\0\1\4\3\0"+
    "\1\4\1\0\2\4\1\0\3\4\3\0\25\4\1\130"+
    "\12\0\1\4\3\0\1\4\1\0\2\4\1\0\3\4"+
    "\3\0\14\4\1\131\11\4\12\0\1\4\3\0\1\4"+
    "\1\0\2\4\1\0\3\4\3\0\11\4\1\132\14\4"+
    "\12\0\1\4\3\0\1\4\1\0\2\4\55\0\1\133"+
    "\2\0\3\4\3\0\1\4\1\134\24\4\12\0\1\4"+
    "\3\0\1\4\1\0\2\4\1\0\3\4\3\0\16\4"+
    "\1\135\7\4\12\0\1\4\3\0\1\4\1\0\2\4"+
    "\1\0\3\4\3\0\4\4\1\136\21\4\12\0\1\4"+
    "\3\0\1\4\1\0\2\4\1\0\3\4\3\0\1\4"+
    "\1\137\24\4\12\0\1\4\3\0\1\4\1\0\2\4"+
    "\1\0\3\4\3\0\13\4\1\140\12\4\12\0\1\4"+
    "\3\0\1\4\1\0\2\4\1\0\3\4\3\0\17\4"+
    "\1\141\6\4\12\0\1\4\3\0\1\4\1\0\2\4"+
    "\1\0\3\4\3\0\12\4\1\142\13\4\12\0\1\4"+
    "\3\0\1\4\1\0\2\4\1\0\3\4\3\0\12\4"+
    "\1\143\13\4\12\0\1\4\3\0\1\4\1\0\2\4"+
    "\1\0\3\4\3\0\1\4\1\144\24\4\12\0\1\4"+
    "\3\0\1\4\1\0\2\4\1\0\3\4\3\0\7\4"+
    "\1\145\16\4\12\0\1\4\3\0\1\4\1\0\2\4"+
    "\1\0\3\4\3\0\4\4\1\146\21\4\12\0\1\4"+
    "\3\0\1\4\1\0\2\4\1\0\3\4\3\0\2\4"+
    "\1\147\23\4\12\0\1\4\3\0\1\4\1\0\2\4"+
    "\1\0\3\4\3\0\5\4\1\150\20\4\12\0\1\4"+
    "\3\0\1\4\1\0\2\4\1\0\3\4\3\0\7\4"+
    "\1\151\16\4\12\0\1\4\3\0\1\4\1\0\2\4"+
    "\1\0\3\4\3\0\2\4\1\152\23\4\12\0\1\4"+
    "\3\0\1\4\1\0\2\4\1\0\3\4\3\0\2\4"+
    "\1\153\23\4\12\0\1\4\3\0\1\4\1\0\2\4"+
    "\15\0\1\154\42\0\3\4\3\0\4\4\1\155\21\4"+
    "\12\0\1\4\3\0\1\4\1\0\2\4\1\0\3\4"+
    "\3\0\1\4\1\156\24\4\12\0\1\4\3\0\1\4"+
    "\1\0\2\4\1\0\3\4\3\0\1\4\1\157\24\4"+
    "\12\0\1\4\3\0\1\4\1\0\2\4\1\0\3\4"+
    "\3\0\2\4\1\160\23\4\12\0\1\4\3\0\1\4"+
    "\1\0\2\4\1\0\3\4\3\0\4\4\1\161\21\4"+
    "\12\0\1\4\3\0\1\4\1\0\2\4\1\0\3\4"+
    "\3\0\10\4\1\162\15\4\12\0\1\4\3\0\1\4"+
    "\1\0\2\4\1\0\3\4\3\0\5\4\1\163\20\4"+
    "\12\0\1\4\3\0\1\4\1\0\2\4\1\0\3\4"+
    "\3\0\2\4\1\164\23\4\12\0\1\4\3\0\1\4"+
    "\1\0\2\4\1\0\3\4\3\0\4\4\1\165\21\4"+
    "\12\0\1\4\3\0\1\4\1\0\2\4\1\0\3\4"+
    "\3\0\25\4\1\166\12\0\1\4\3\0\1\4\1\0"+
    "\2\4\1\0\3\4\3\0\1\4\1\167\24\4\12\0"+
    "\1\4\3\0\1\4\1\0\2\4\1\0\3\4\3\0"+
    "\4\4\1\170\21\4\12\0\1\4\3\0\1\4\1\0"+
    "\2\4\24\0\1\171\33\0\3\4\3\0\5\4\1\172"+
    "\20\4\12\0\1\4\3\0\1\4\1\0\2\4\1\0"+
    "\3\4\3\0\4\4\1\173\21\4\12\0\1\4\3\0"+
    "\1\4\1\0\2\4\1\0\3\4\3\0\4\4\1\174"+
    "\21\4\12\0\1\4\3\0\1\4\1\0\2\4\1\0"+
    "\3\4\3\0\16\4\1\175\7\4\12\0\1\4\3\0"+
    "\1\4\1\0\2\4\1\0\3\4\3\0\12\4\1\176"+
    "\13\4\12\0\1\4\3\0\1\4\1\0\2\4\1\0"+
    "\3\4\3\0\13\4\1\177\12\4\12\0\1\4\3\0"+
    "\1\4\1\0\2\4\1\0\3\4\3\0\7\4\1\200"+
    "\16\4\12\0\1\4\3\0\1\4\1\0\2\4\1\0"+
    "\3\4\3\0\11\4\1\201\14\4\12\0\1\4\3\0"+
    "\1\4\1\0\2\4\56\0\1\202\1\0\3\4\3\0"+
    "\4\4\1\203\21\4\12\0\1\4\3\0\1\4\1\0"+
    "\2\4\1\0\3\4\3\0\14\4\1\204\11\4\12\0"+
    "\1\4\3\0\1\4\1\0\2\4\1\0\3\4\3\0"+
    "\10\4\1\205\15\4\12\0\1\4\3\0\1\4\1\0"+
    "\2\4\1\0\3\4\3\0\17\4\1\206\6\4\12\0"+
    "\1\4\3\0\1\4\1\0\2\4\1\0\3\4\3\0"+
    "\1\4\1\207\24\4\12\0\1\4\3\0\1\4\1\0"+
    "\2\4\1\0\3\4\3\0\2\4\1\210\23\4\12\0"+
    "\1\4\3\0\1\4\1\0\2\4\1\0\3\4\3\0"+
    "\1\4\1\211\24\4\12\0\1\4\3\0\1\4\1\0"+
    "\2\4\55\0\1\212\2\0\3\4\3\0\12\4\1\213"+
    "\13\4\12\0\1\4\3\0\1\4\1\0\2\4\1\0"+
    "\3\4\3\0\1\4\1\214\24\4\12\0\1\4\3\0"+
    "\1\4\1\0\2\4\1\0\3\4\3\0\2\4\1\215"+
    "\23\4\12\0\1\4\3\0\1\4\1\0\2\4\52\0"+
    "\1\216\5\0\3\4\3\0\2\4\1\217\23\4\12\0"+
    "\1\4\3\0\1\4\1\0\2\4\1\0\3\4\3\0"+
    "\4\4\1\220\21\4\12\0\1\4\3\0\1\4\1\0"+
    "\2\4\54\0\1\221\3\0\3\4\3\0\13\4\1\222"+
    "\12\4\12\0\1\4\3\0\1\4\1\0\2\4\1\0"+
    "\3\4\3\0\7\4\1\223\16\4\12\0\1\4\3\0"+
    "\1\4\1\0\2\4\1\0\3\4\3\0\14\4\1\224"+
    "\11\4\12\0\1\4\3\0\1\4\1\0\2\4";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5358];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\17\1\2\11\2\1\5\11"+
    "\1\1\3\11\21\1\3\11\2\1\1\0\21\1\1\0"+
    "\20\1\1\0\20\1\1\0\14\1\1\0\10\1\1\0"+
    "\7\1\1\0\3\1\1\0\2\1\1\11\3\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[148];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
public boolean fin=false;
public String lexema="";
public int linea;
public int columna;

public void imprime(){
    System.out.println(lexema);
}


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Yylex(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 11: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.IGUAL, new token(yytext(),yyline,yycolumn));
          }
        case 42: break;
        case 6: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.MAS, new token(yytext(),yyline,yycolumn));
          }
        case 43: break;
        case 15: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.PCOMA, new token(yytext(),yyline,yycolumn));
          }
        case 44: break;
        case 3: 
          { lexema+="ID: "+(yytext())+"\n";  return new Symbol(sym.ID, new token(yytext(),yyline,yycolumn));
          }
        case 45: break;
        case 23: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.MAYORIG, new token(yytext(),yyline,yycolumn));
          }
        case 46: break;
        case 12: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.NO, new token(yytext(),yyline,yycolumn));
          }
        case 47: break;
        case 1: 
          { lexema+="Error Léxico : "+yytext()+ " en la linea "+(yyline+1)+" columna "+yycolumn+"\n";   return new Symbol(sym.error,new token(yytext(),yyline,yycolumn));
          }
        case 48: break;
        case 19: 
          { lexema+="Decimal: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.NDECIMAL, new token(yytext(),yyline,yycolumn));
          }
        case 49: break;
        case 18: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.PARENC, new token(yytext(),yyline,yycolumn));
          }
        case 50: break;
        case 38: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.VERDADERO, new token(yytext(),yyline,yycolumn));
          }
        case 51: break;
        case 28: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.CICLO, new token(yytext(),yyline,yycolumn));
          }
        case 52: break;
        case 29: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.ENTERO, new token(yytext(),yyline,yycolumn));
          }
        case 53: break;
        case 16: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.COMA, new token(yytext(),yyline,yycolumn));
          }
        case 54: break;
        case 21: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.DISTINTO, new token(yytext(),yyline,yycolumn));
          }
        case 55: break;
        case 25: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.PARAR, new token(yytext(),yyline,yycolumn));
          }
        case 56: break;
        case 36: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.IMPRIMIR, new token(yytext(),yyline,yycolumn));
          }
        case 57: break;
        case 17: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.PARENA, new token(yytext(),yyline,yycolumn));
          }
        case 58: break;
        case 13: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.Y, new token(yytext(),yyline,yycolumn));
          }
        case 59: break;
        case 14: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.O, new token(yytext(),yyline,yycolumn));
          }
        case 60: break;
        case 32: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.VECTOR, new token(yytext(),yyline,yycolumn));
          }
        case 61: break;
        case 40: 
          { lexema+="Cadena: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.DCADENA, new token(yytext(),yyline,yycolumn));
          }
        case 62: break;
        case 41: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.DECLARACIONES, new token(yytext(),yyline,yycolumn));
          }
        case 63: break;
        case 9: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.MENOR, new token(yytext(),yyline,yycolumn));
          }
        case 64: break;
        case 2: 
          { lexema+="Entero: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.NENTERO, new token(yytext(),yyline,yycolumn));
          }
        case 65: break;
        case 8: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.DIVIDENDO, new token(yytext(),yyline,yycolumn));
          }
        case 66: break;
        case 10: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.MAYOR, new token(yytext(),yyline,yycolumn));
          }
        case 67: break;
        case 31: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.INICIO, new token(yytext(),yyline,yycolumn));
          }
        case 68: break;
        case 24: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.FIN, new token(yytext(),yyline,yycolumn));
          }
        case 69: break;
        case 37: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.BOOLEANO, new token(yytext(),yyline,yycolumn));
          }
        case 70: break;
        case 35: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.MIENTRAS, new token(yytext(),yyline,yycolumn));
          }
        case 71: break;
        case 20: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.SI, new token(yytext(),yyline,yycolumn));
          }
        case 72: break;
        case 27: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.FALSO, new token(yytext(),yyline,yycolumn));
          }
        case 73: break;
        case 39: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.ESTRUCTURA, new token(yytext(),yyline,yycolumn));
          }
        case 74: break;
        case 22: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.MENORIG, new token(yytext(),yyline,yycolumn));
          }
        case 75: break;
        case 33: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.DECIMAL, new token(yytext(),yyline,yycolumn));
          }
        case 76: break;
        case 26: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.DESDE, new token(yytext(),yyline,yycolumn));
          }
        case 77: break;
        case 34: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.PROGRAMA,new token(yytext(),yyline,yycolumn));
          }
        case 78: break;
        case 7: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.POR, new token(yytext(),yyline,yycolumn));
          }
        case 79: break;
        case 5: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.MENOS, new token(yytext(),yyline,yycolumn));
          }
        case 80: break;
        case 30: 
          { lexema+="Token: "+(yytext()).toUpperCase()+"\n";  return new Symbol(sym.CADENA, new token(yytext(),yyline,yycolumn));
          }
        case 81: break;
        case 4: 
          { 
          }
        case 82: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {  fin=true;
return new Symbol(sym.EOF,new String("Fin del archivo"));
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
